config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #home page

  root to: "home#index"

  # get '/', to: 'home#', as: 'home'

  #about page
  get '/about', to: 'home#about', as: 'about'

  #signin/sessions

  get '/signin', to: 'sessions#new'

  #create a session
  post '/sessions', to: 'sessions#create'

  #delete session
  delete '/sessions', to: 'sessions#destroy'

  #contact form
  get '/contact', to: 'contact#index'



  resources :lawyers, :clients, :sessions, :blog



end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base


	attr_accessor :user_t


	# validates :email, presence: true, uniqueness:true, confirmation: true
	validates :first_name, presence: true
	validates :last_name, presence: true

	belongs_to :lawyer

	# def self.confirm(params)
	# 	@client = Client.find_by({email: params[:email]})
	# 	@client.try(:authenticate, params[:password])
	# end

end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base


	attr_accessor :user_t

	# validates :email, presence: true, uniqueness:true, confirmation: true
	validates :first_name, presence: true
	validates :last_name, presence: true

	has_many :clients

	# def self.confirm(params)
	# 	@lawyer = Lawyer.find_by({email: params[:email]})
	# 	@lawyer.try(:authenticate, params[:password])
	# end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  include SessionsHelper


  private

  def require_login
    if !current_user
      flash[:error] = "Please login or create an account!"
      redirect_to '/'
    end
  end


  def is_lawyer
    if current_user.user_t == 'lawyers'
    else
      flash[:error] = "Only an attorney may view this!"
      redirect_to '/'
    end
  end

  
  def is_client
    if current_user.user_t == 'clients'
    else
      flash[:error] = "Only a client may view this!"
      redirect_to '/'
    end
  end


  def client_profile?
    if current_user.user_t == 'clients'
      if current_user.id.to_s != params[:id]
        flash[:error] = "You are not authorized to view this!"
        redirect_to "/clients/#{current_user.id}"
      end
    end
  end


  def lawyer_profile?
    if current_user.id.to_s != params[:id]
      flash[:error] = "Only an attorney may view this!"
      redirect_to "/lawyers/#{current_user.id}"
    end
  end




end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
		render :index
	end

	def about
		render :about
	end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_action :require_login, :except => [:new, :create, :index, :show]
	before_action :is_client, only:[:edit]
	before_action :client_profile?, only:[:edit, :show]

	def index
		@clients = Client.all
		render :index
	end

	def new
		@client = Client.new
		render :new
	end

	def create
		@client = Client.new(client_params)
			if @client.save
				login(@client, 'clients')
				redirect_to "/clients/#{@client.id}"/lawyer_list
			else
				redirect_to 'clients/new'
			end
		end

		def show
			@client = Client.find(params[:id])
			@lawyer = @client.lawyer
		end

		def update
			@client = Client.find(params[:id])
			@client.update_attributes(client_params)

			if @client.update_attributes(client_params)
				flash[:success] = "Profile updated!"
				redirect_to "/clients/#{@client.id}"
			else
				render :edit
			end
		end

		def destroy
			@client = Client.find(params[:id])
			@client.destroy
			redirect_to '/'
		end

		private 

		def client_params
			params.require(:client).permit(:first_name, :last_name, :location, :description, :image_url, :phone)
		end


end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	def index
		render :index
	end

	def about
		render :about
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
		render :about
	end

end

app/controllers/lawyers_controller.rb
class LawyersController < ApplicationController

	# before_action :require_login, :except => [:index, :new, :show, :create]

	# before_action :lawyer_profile?, only:[:edit]

	def index 
		@lawyers = Lawyer.all
		render :index
	end

	def new
		@lawyer = Lawyer.new
		render :new
	end


	def show
		@lawyer = Lawyer.find(params[:id])
		render :show
	end

	def create
		@lawyer = Lawyer.new(lawyer_params)
		if @lawyer.save
			login(@lawyer, 'lawyers')
			flash[:success] = "Profile created!"
			redirect_to "/lawyers/#{@lawyer.id}"
		else
			flash[:error] = @lawyer.errors.full_messages.join("---")
			redirect_to '/lawyers/new'
		end
	end

	def edit
		@lawyer = Lawyer.find(params[:id])
		render :edit
	end

	#update client's profile?
	def update
		@lawyer = Lawyer.find(params[:id])
		@lawyer.update_attributes(lawyer_params)

		if @lawyer.update_attributes(lawyer_params)
			redirect_to "/lawyers/#{@lawyer.id}"
			flash[:notice] = "Profile Updated!"
		else
			flash[:error] = @lawyer.errors.full_messages.join("---")
			render :edit
		end
	end

	private

	def lawyer_params
		params.require(:lawyer).permit(:first_name, :last_name, :location, :years_experience, :practice_areas)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		render :new
	end

	def create
	  	user = params.require(:user).permit(:email, :password)
	  	@user = Lawyer.find_by_email(user[:email])
	  	if @user != nil
	  		@user= Lawyer.confirm(user)
	  		user_t = "lawyers"
	  	else
	  		@user = Client.confirm(user)
	  		user_t = "clients"
	  	end

		if @user
			login(@user, user_t)
			redirect_to "/#{user_t}/#{@user.id}"
		else
	    	flash[:error] = 'Invalid email/password combination'

			redirect_to "/signin"
		end
	end

	def destroy
		logout
		redirect_to '/'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when :notice then "alert alert-info"
			when :success then "alert alert-success"
			when :error then "alert alert-error"
			when :alert then "alert alert-error"
		end
	end



end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user, user_t)
    session[:user_id] = user.id
    session[:user_t] = user_t
  end

  def user_type
  end

  def current_user
    if session[:user_id] != nil
      if session[:user_t] == "clients"
        @current_user ||= session[:user_id] && Client.find(session[:user_id])
        @current_user.user_t = "clients"
      else
        @current_user ||= session[:user_id] && Lawyer.find(session[:user_id])
        @current_user.user_t = "lawyers"
      end
      return @current_user
    end
  end

  def logged_in?
    if @current_user == nil
      redirect_to "/signin"
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_t] = nil
    @current_user = nil
    session.delete(:user_id)
  end

end

app/views/application/_footer.html.erb
<footer>
<h1>footer partial</h1>
  <ul>
    <li>About us</li>
    <li>Team</li>
    <li>Terms and conditions</li>
  </ul>
</footer>

app/views/blog/index.html.erb
<body>
<div class="row">
		<div class="medium-7 large-6 columns">
			<h1>About Lexa</h1>
			<p class="subheader">Lexa is the place to find great lawyers fast. Easily create a client account, search for lawyers by location or practice area, and connect with lawyers fast.</p>
			<p class="subheader">Lexa was founded in 2016 under the belief that legal access should be more democratic. Someone who needs legal help should be able to find it quickly and easily, and economic means should not be a prohibitive factor in quality legal representation.</p>
			<p class="subheader">Lexa is the place to find great lawyers fast. Easily create a client account, search for lawyers by location or practice area, and connect with lawyers fast.</p>
			<%= link_to "About", :about, :class => "button" %>
			<%= link_to "Sign Up", :about, :class => "button" %>
		</div>

		<div class="show-for-large large-3 columns">
			<img src="http://placehold.it/400x370&text=PSR1257 + 12 C" alt="picture of space">
		</div>

		<div class="medium-5 large-3 columns">
		<div class="callout secondary">
			<form>
				<div class="row">
				<div class="small-12 columns">
					<label>Find Your Dream Planet
					<input type="text" placeholder="Search destinations">
					</label>
				</div>
		<div class="small-12 columns">
			<label>Number of Moons
			<input type="number" placeholder="Moons required">
			</label>
			<button type="submit" class="button">Search Now!</button>
			</div>
		</div>
		</form>
	</div>
</div>
</div>




</div>

app/views/clients/edit.html.erb
<h1>Edit Profile</h1>


  <%= form_for @client, url: client_path(@client), method: :patch do |f| %>

  <div>

  <%= f.text_field :first_name, placeholder: "First Name" %> <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
  <%= f.text_field :email, placeholder: "Email" %> <%= f.text_field :confirm_email, placeholder: "Confirm Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %> <%= f.password_field :confirm_password, placeholder: "Confirm Password" %>
  </div>

    <div>
    <%= f.text_field :location, placeholder: "Location" %>
  </div>


  <div>
    <%= f.text_field :description, placeholder: "Legal Issues" %>
  </div>


  <br>

  <div>
      <%= f.hidden_field :image_url, role: "uploadcare-uploader" %>
  </div>


  <%= f.submit "Update Profile" %>


  <% end %>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
  </div>

app/views/clients/index.html.erb
<div class="container">

<h1>Clients</h1>

	<% @clients.each do |client| %>
		<div class="client">
			<h2><%= link_to client.first_name + " " + client.last_name, client_path(client) %> </h2>
			<div class="column"><img class="image" src="<%= client.image_url %>" alt="image for client" width="150px" height="150px">
			</div>

		<h2>Location: <%= client.location %> </h2>
		<h2>Legal Issue: <%= client.description%> </h2>
		<div class="clearfix"></div>
	</div>
	<% end %>
</div>

app/views/clients/new.html.erb
<div class="client">
<h1>Create a New User Account</h1>
<%= simple_form_for @client do |f| %>
  <%= f.input :first_name, label: 'First Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :last_name, label: 'Last Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :location, label: 'Location', error: 'Username is mandatory, please specify one' %>
  <%= f.button :submit, "Create Account", class: "button" %>
<% end %>
</div>

app/views/clients/sessions.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/clients/show.html.erb
<div class="client">
      <img class = 'image' src="<%= @client.image_url %>" alt="image for client" width='150px'>


  <div><h2><%= @client.first_name + " " + @client.last_name %></h2></div>
  <div><b>Email:</b> <%= @client.email %></div>
  <div><b>Phone:</b> <%= @client.phone %></div>
  <div><b>Location:</b> <%= @client.location %></div>
  <div><b>Client Since:</b> <%= @client.created_at.strftime("%b %d, %Y") %></div>
  <br>

    
</div>

</div>
  <br>
</div>

<div class="row">
  <div class="client">

<%if @lawyer %>

  <h3>Your Attorney</h3>

    <img src="<%= @lawyer.image_url %>" width="80px" alt="lawyer image"/>


    <h6><%= link_to @lawyer.first_name + " " + @lawyer.last_name, lawyer_path(@lawyer)%></h6>
    <%= @lawyer.description %><br>                      


    <%= link_to "Change Attorney", :about %>

      <% else %>
        <div>
          <h4>No Current Attorney</h4>
        </div>
      <% end %>
    <div>
</div>

app/views/home/about.html.erb
<body>
<div class="row">
		<div class="medium-7 large-6 columns">
			<h1>Close Your Eyes and Open Your Mind</h1>
			<p class="subheader">Lexa is the place to find great lawyers fast. Easily create a client account, search for lawyers by location or practice area, and connect with lawyers fast.</p>
			<button class="button">Take a Tour</button>
			<button class="button">Start a free trial</button>
		</div>

		<div class="show-for-large large-3 columns">
			<img src="http://placehold.it/400x370&text=PSR1257 + 12 C" alt="picture of space">
		</div>

		<div class="medium-5 large-3 columns">
		<div class="callout secondary">
			<form>
				<div class="row">
				<div class="small-12 columns">
					<label>Find Your Dream Planet
					<input type="text" placeholder="Search destinations">
					</label>
				</div>
		<div class="small-12 columns">
			<label>Number of Moons
			<input type="number" placeholder="Moons required">
			</label>
			<button type="submit" class="button">Search Now!</button>
			</div>
		</div>
		</form>
	</div>
</div>
</div>


	<div class="row column">
		<hr>
	</div>

	<div class="row column">
		<p class="lead">Trending Planetary Destinations</p>
	</div>

	<div class="row small-up-1 medium-up-2 large-up-3">

	<div class="column">

	<div class="callout">
		<p>Pegasi B</p>

		<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>

		<p class="lead">Copernican Revolution caused an uproar</p>

		<p class="subheader">Find Earth-like planets life outside the Solar System</p>
	</div>
</div>


</div>

app/views/home/home.html.erb
<body>
<div class="row">
		<div class="medium-7 large-6 columns">
			<h1>Find a great lawyer, fast</h1>
			<p class="subheader">Lexa is the place to find great lawyers fast. Easily create a client account, search for lawyers by location or practice area, and connect with lawyers fast.</p>
			<%= link_to "How It Works", :about, :class => "button" %>
			<%= link_to "Sign Up", '/clients/new', :class => "button" %><br>
			<%= link_to "For Attorneys", '/lawyers/new', :class => "button" %>

		</div>

		<div class="show-for-large large-3 columns">
			<img src="http://placehold.it/400x370&text=PSR1257 + 12 C" alt="picture of space">
		</div>

		<div class="medium-5 large-3 columns">
		<div class="callout secondary">
			<form>
				<div class="row">
				<div class="small-12 columns">
					<label>Find a Qualified Attorney Right Away
					<input type="text" placeholder="Enter Legal Issue">
					</label>
				</div>
		<div class="small-12 columns">
			<label>Location
			<input type="number" placeholder="Location">
			</label>
			<button type="submit" class="button">Search</button>
			</div>
		</div>
		</form>
	</div>
</div>
</div>


	<div class="row column">
		<hr>
	</div>

	<div class="row column">
		<p class="lead">Lexa Has You Covered For All Your Legal Needs</p>
	</div>

	<div class="row small-up-1 medium-up-2 large-up-3">

	<div class="column">

	<div class="callout">
		<h3>Employment</h3>

		<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>

		<p class="lead">Employment and workplace fairness attorneys</p>

		<p class="subheader">Find the best attorney for your workplace situation</p>
	</div>
</div>


	<div class="column">
		<div class="callout">
			<h3>Immigration</h3>
			<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>
			<p class="lead">Come to the US with confidence</p>
			<p class="subheader">Visas, green cards, and other immigration matters</p>
		</div>
	</div>


	<div class="column">
		<div class="callout">
			<h3>Startups</h3>
			<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>
			<p class="lead">LLC or C Corp?</p>
			<p class="subheader">Connect with a great attorney so you can get on to creating your great company</p>
		</div>
	</div>

	<div class="column">
		<div class="callout">
			<h3>Estate Planning</h3>
			<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>
			<p class="lead">Trusts, wills and estates</p>
			<p class="subheader">Protect your assets</p>
		</div>
	</div>


	<div class="column">
		<div class="callout">
			<h3>Personal Injury</h3>
			<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>
			<p class="lead">Accidents, DUIs, etc.</p>
			<p class="subheader">Recover for harm and losses due to negligence</p>
		</div>
	</div>

	<div class="column">
		<div class="callout">
			<h3>Real Estate</h3>
			<p><img src="http://placehold.it/400x370&text=Pegasi B" alt="image of a planet called Pegasi B"></p>
			<p class="lead">Property Lawyers</p>
			<p class="subheader">Keep what's rightfully yours and stuff</p>
		</div>
	</div>
</div>



	</body>

app/views/lawyers/edit.html.erb
<h1>Edit Profile</h1>


  <%= form_for @lawyer, url: lawyer_path(@lawyer), method: :patch do |f| %>

  <div>

  <%= f.text_field :first_name, placeholder: "First Name" %> <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
  <%= f.text_field :email, placeholder: "Email" %> <%= f.text_field :confirm_email, placeholder: "Confirm Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %> <%= f.password_field :confirm_password, placeholder: "Confirm Password" %>
  </div>

    <div>
    <%= f.text_field :location, placeholder: "Location" %>
  </div>
  

    <div>
    <%= f.text_field :practice_areas, placeholder: "Practice Areas" %>
  </div>



  <div>
    <%= f.text_field :description, placeholder: "Education, degrees, and specialty" %>
  </div>


  <br>

  <div>
      <%= f.hidden_field :image_url, role: "uploadcare-uploader" %>
  </div>


  <%= f.submit "Update Profile" %>


  <% end %>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
  </div>

app/views/lawyers/index.html.erb
<div class="container">

<h1>Lawyers</h1>

	<% @lawyers.each do |lawyer| %>
		<div class="lawyer">
			<h2><%= link_to lawyer.first_name + " " + lawyer.last_name, lawyer_path(lawyer) %> </h2>
			<div class="column"><img class="image" src="<%= lawyer.image_url %>" alt="image for laywer" width="150px">
			</div>

		<h3>Location: <%= lawyer.location %> </h3>
		<h3>Practice Areas: <%= lawyer.practice_areas %> </h3>
		<h3>Years Experience: <%= lawyer.years_experience%> </h3>
		<div class="clearfix"></div>
	</div>
	<% end %>
</div>

app/views/lawyers/new.html.erb
<div class="lawyer">
<h1>Create a New Attorney Account</h1>
<%= simple_form_for @lawyer do |f| %>
  <%= f.input :first_name, label: 'First Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :last_name, label: 'Last Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :location, label: 'Location', error: 'Username is mandatory, please specify one' %>
  <%= f.input :years_experience, label: 'Years Experience', error: 'Username is mandatory, please specify one' %>
 <%= f.input :practice_areas, label: 'Practice Areas', error: 'Username is mandatory, please specify one' %>
  <%= f.button :submit, "Create Account", class: "button" %>
<% end %>
</div>

app/views/lawyers/sessions.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/lawyers/show.html.erb
<div class="lawyer">
	<h2><%= link_to @lawyer.first_name + " " + @lawyer.last_name, lawyer_path(@lawyer) %> </h2>
	<div class="column"><img class="image" src="<%= @lawyer.image_url %>" alt="image for laywer" width="150px">
			</div>
	<h2>Location: <%= @lawyer.location %> </h2>
	<h2>Practice Areas: <%= @lawyer.practice_areas %> </h2>
	<h2>Years Experience: <%= @lawyer.years_experience%> </h2>
	<h3>Email: <%= @lawyer.email %></h3></div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>


    	<%= stylesheet_link_tag    "application" %>
    	<%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    	<%= csrf_meta_tags %>

		<link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">

		<link href='http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>

		<!-- foundation css motion-ui library -->
   		 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />

	<!-- uploadcare -->
  	<script>UPLOADCARE_PUBLIC_KEY = "b87de74d4f4e35f8c03e";</script>
	<script src="https://ucarecdn.com/widget/2.9.0/uploadcare/uploadcare.full.min.js" charset="utf-8"></script>

	</head>

  <body>
  	<div class="top-bar" id="lexaMenu">

		<div class="top-bar-left">

			<ul class="menu" data-responsive-menu="accordion">
				<li class="menu-text"><%= link_to 'Lexa', '/' %></li>
				<li><%= link_to 'About', :about %>
				<li><%= link_to 'Lawyers', '/lawyers' %>
				<li><a href="#">FAQ</a></li>
				<li><%= link_to 'Blog', '/blog' %>
				<li><%= link_to 'Contact', '/contact' %>
			</ul>
		</div>
	
	<nav>
		<ul>
		<% if current_user != nil %>
          <%if current_user.user_t == 'lawyers' %>
              <li><%= link_to "Clients", '/clients' %></li>
              <li><%= link_to "Profile", lawyer_path(current_user) %></li>
              <%else%>
              <li><%= link_to "Lawyers", '/lawyers' %></li>
              <li><%= link_to "Profile", client_path(current_user) %></li>
              <%end%>

              <li><%= link_to "Log Out", '/sessions', method: :delete, :class => "button" %></li>

              <% else %>

              
             <%end%>
        </ul>
        </nav>



	<div class="top-bar-right">
		<ul class="menu">
			<li><%= link_to "Home", "/" %></li>
			<li><a href="#">My Account</a></li>
			<li><%= link_to "Log In", '/signin', :class => "button" %> </li>
		</ul>
	</div>
</div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>



    <%= yield %>

  <footer>
	<div class="row expanded callout secondary">
		<div class="small-6 large-3 columns">
			<p class="lead">Offices</p>
		<ul class="menu vertical">
			<li><a href="#">SF</a></li>
			<li><a href="#">NYC</a></li> 
		</ul>
	</div>

	<div class="small-6 large-3 columns">
		<p class="lead">Know Your Rights</p>
		<ul class="menu vertical">
			<li><a href="#">Legal Reference</a></li>
			<li><a href="#">ABA</a></li>
		</ul>
	</div>


	<div class="small-6 large-3 columns">
		<p class="lead">Contact</p>
		<ul class="menu vertical">
			<li><a href="#"><i class="fi-social-twitter"></i> Twitter</a></li>
			<li><a href="#"><i class="fi-social-facebook"></i> Facebook</a></li>
		</ul>
	</div>

	<div class="small-6 large-3 columns">
		<p class="lead">Locations</p>
		<ul class="menu vertical">
			<li><a href="#">SF</a></li>
			<li><a href="#">NYC</a></li>
		</ul>
	</div>
</div>


	<div class="row">
		<div class="medium-6 columns">
			<ul class="menu">
				<li><%= link_to 'About', :about %>
				<li><%= link_to 'Lawyers', '/lawyers' %>
				<li><%= link_to 'Blog', '/blog' %>
				<li><%= link_to 'Contact', '/contact' %>
			</ul>
		</div>


	<div class="medium-6 columns">
		<ul class="menu float-right">
			<li class="menu-text">Copyright 2016</li>
		</ul>
	</div>
  </div>
</footer>

<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


</body>
</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sidebar Template</title>
</head>
<body>
  <header>
    <h1>My Website</h1>  
    <ul>
      <li>Menu 1</li>
      <li>Menu 2</li>
      <li>Menu 3</li>
      <li>Menu 4</li>
    </ul>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <ul>
      <li>About us</li>
      <li>Team</li>
      <li>Terms and conditions</li>
    </ul>
  </footer>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>